name: nextron-python-sample
channels:
  - fastai
  - peterjc123
  - pytorch
  - defaults
dependencies:
  - certifi=2018.10.15=py37_0
  - cffi=1.11.5=py37h74b6da3_1
  - click=7.0=py37_0
  - flask=1.0.2=py37_1
  - future=0.16.0=py37_0
  - gevent=1.3.7=py37he774522_1
  - greenlet=0.4.15=py37hfa6e2cd_0
  - itsdangerous=1.1.0=py37_0
  - jinja2=2.10=py37_0
  - markupsafe=1.0=py37hfa6e2cd_1
  - msgpack-python=0.5.6=py37he980bc4_1
  - pip=10.0.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.1=h33f27b4_4
  - setuptools=40.4.3=py37_0
  - werkzeug=0.14.1=py37_0
  - wheel=0.32.2=py37_0
  - wincertstore=0.2=py37_0
  - vc=14.1=h21ff451_1
  - vs2017_runtime=15.4.27004.2010=1
  - pip:
    - flask-cors
    - flask-graphql
    - graphene
    - pyinstaller
    - pypiwin32
